// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
<<<<<<< HEAD
// Autogenerated from Pigeon (v26.1.0), do not edit directly.
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
// Autogenerated from Pigeon (v22.4.0), do not edit directly.
=======
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

/// Possible outcomes of an authentication attempt.
<<<<<<< HEAD
enum AuthResultCode {
  /// The user authenticated successfully.
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
enum AuthResult {
  /// The user authenticated successfully.
=======
enum AuthResult {
  /// The user authenticated successfully and no biometric checking was done.
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  success,
<<<<<<< HEAD

  /// The user pressed the negative button, which corresponds to
  /// [AuthStrings.cancelButton].
  negativeButton,

  /// The user canceled authentication without pressing the negative button.
  ///
  /// This may be triggered by a swipe or a back button, for example.
  userCanceled,

  /// Authentication was caneceled by the system.
  systemCanceled,

  /// Authentication timed out.
  timeout,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)

  /// The user failed to successfully authenticate.
  failure,

=======
  /// The user authenticated successfully, and biometric checking was true.
  successValidated,
  /// The user authenticated successfully, and biometric checking was false.
  successInvalidated,
  /// The user failed to successfully authenticate.
  failure,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// An authentication was already in progress.
<<<<<<< HEAD
  alreadyInProgress,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorAlreadyInProgress,

=======
  errorAlreadyInProgress,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// There is no foreground activity.
<<<<<<< HEAD
  noActivity,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorNoActivity,

=======
  errorNoActivity,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// The foreground activity is not a FragmentActivity.
<<<<<<< HEAD
  notFragmentActivity,

  /// The device does not have any credentials available.
  noCredentials,

  /// No biometric hardware is present.
  noHardware,

  /// The biometric is temporarily unavailable.
  hardwareUnavailable,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorNotFragmentActivity,

  /// The authentication system was not available.
  errorNotAvailable,

=======
  errorNotFragmentActivity,
  /// The authentication system was not available.
  errorNotAvailable,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// No biometrics are enrolled.
<<<<<<< HEAD
  notEnrolled,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorNotEnrolled,

=======
  errorNotEnrolled,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// The user is locked out temporarily due to too many failed attempts.
<<<<<<< HEAD
  lockedOutTemporarily,

||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorLockedOutTemporarily,

=======
  errorLockedOutTemporarily,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  /// The user is locked out until they log in another way due to too many
  /// failed attempts.
<<<<<<< HEAD
  lockedOutPermanently,

  /// The device does not have enough storage to complete authentication.
  noSpace,

  /// The hardware is unavailable until a security update is performed.
  securityUpdateRequired,

  /// Some unrecognized error case was encountered
  unknownError,
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  errorLockedOutPermanently,
=======
  errorLockedOutPermanently,
  /// Biometric checking failed.
  errorBiometricChecking,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
}

/// Pigeon equivalent of the subset of BiometricType used by Android.
enum AuthClassification { weak, strong }

/// Pigeon version of AndroidAuthStrings, plus the authorization reason.
///
/// See auth_messages_android.dart for details.
class AuthStrings {
  AuthStrings({
    required this.reason,
    required this.signInHint,
    required this.cancelButton,
    required this.signInTitle,
  });

  String reason;

  String signInHint;

  String cancelButton;

  String signInTitle;

  List<Object?> _toList() {
    return <Object?>[reason, signInHint, cancelButton, signInTitle];
  }

  Object encode() {
    return _toList();
  }

  static AuthStrings decode(Object result) {
    result as List<Object?>;
    return AuthStrings(
      reason: result[0]! as String,
      signInHint: result[1]! as String,
      cancelButton: result[2]! as String,
      signInTitle: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthStrings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// The results of an authentication request.
class AuthResult {
  AuthResult({required this.code, this.errorMessage});

  /// The specific result returned from the SDK.
  AuthResultCode code;

  /// The error message associated with the result, if any.
  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[code, errorMessage];
  }

  Object encode() {
    return _toList();
  }

  static AuthResult decode(Object result) {
    result as List<Object?>;
    return AuthResult(
      code: result[0]! as AuthResultCode,
      errorMessage: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class AuthOptions {
  AuthOptions({
    required this.biometricOnly,
    required this.sensitiveTransaction,
    required this.sticky,
<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    required this.useErrorDialgs,
=======
    required this.useErrorDialgs,
    required this.checkBiometricInvalidationForKey,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  });

  bool biometricOnly;

  bool sensitiveTransaction;

  bool sticky;

  List<Object?> _toList() {
    return <Object?>[biometricOnly, sensitiveTransaction, sticky];
  }

  bool checkBiometricInvalidationForKey;

  Object encode() {
<<<<<<< HEAD
    return _toList();
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    return <Object?>[
      biometricOnly,
      sensitiveTransaction,
      sticky,
      useErrorDialgs,
    ];
=======
    return <Object?>[
      biometricOnly,
      sensitiveTransaction,
      sticky,
      useErrorDialgs,
      checkBiometricInvalidationForKey,
    ];
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  }

  static AuthOptions decode(Object result) {
    result as List<Object?>;
    return AuthOptions(
      biometricOnly: result[0]! as bool,
      sensitiveTransaction: result[1]! as bool,
      sticky: result[2]! as bool,
<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      useErrorDialgs: result[3]! as bool,
=======
      useErrorDialgs: result[3]! as bool,
      checkBiometricInvalidationForKey: result[4]! as bool,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AuthOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
<<<<<<< HEAD
    } else if (value is AuthResultCode) {
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    } else if (value is AuthResult) {
=======
    }    else if (value is AuthResult) {
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AuthClassification) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AuthStrings) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
<<<<<<< HEAD
    } else if (value is AuthResult) {
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    } else if (value is AuthOptions) {
=======
    }    else if (value is AuthOptions) {
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is AuthOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
<<<<<<< HEAD
        return value == null ? null : AuthResultCode.values[value];
      case 130:
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
        return value == null ? null : AuthResult.values[value];
      case 130:
=======
        return value == null ? null : AuthResult.values[value];
      case 130: 
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AuthClassification.values[value];
      case 131: 
        return AuthStrings.decode(readValue(buffer)!);
<<<<<<< HEAD
      case 132:
        return AuthResult.decode(readValue(buffer)!);
      case 133:
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      case 132:
=======
      case 132: 
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
        return AuthOptions.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LocalAuthApi {
  /// Constructor for [LocalAuthApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
<<<<<<< HEAD
  LocalAuthApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  LocalAuthApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
=======
  LocalAuthApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Returns true if this device supports authentication.
  Future<bool> isDeviceSupported() async {
<<<<<<< HEAD
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.isDeviceSupported$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.isDeviceSupported$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
=======
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.isDeviceSupported$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Returns true if this device can support biometric authentication, whether
  /// any biometrics are enrolled or not.
  Future<bool> deviceCanSupportBiometrics() async {
<<<<<<< HEAD
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.deviceCanSupportBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.deviceCanSupportBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
=======
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.deviceCanSupportBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Cancels any in-progress authentication.
  ///
  /// Returns true only if authentication was in progress, and was successfully
  /// cancelled.
  Future<bool> stopAuthentication() async {
<<<<<<< HEAD
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.stopAuthentication$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.stopAuthentication$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
=======
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.stopAuthentication$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Returns the biometric types that are enrolled, and can thus be used
  /// without additional setup.
<<<<<<< HEAD
  ///
  /// Returns null if there is no activity, in which case the enrolled
  /// biometrics can't be determined.
  Future<List<AuthClassification>?> getEnrolledBiometrics() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.getEnrolledBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  Future<List<AuthClassification>> getEnrolledBiometrics() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.getEnrolledBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
=======
  Future<List<AuthClassification>> getEnrolledBiometrics() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.getEnrolledBiometrics$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
<<<<<<< HEAD
      return (pigeonVar_replyList[0] as List<Object?>?)
          ?.cast<AuthClassification>();
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      return (pigeonVar_replyList[0] as List<Object?>?)!
          .cast<AuthClassification>();
=======
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<AuthClassification>();
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    }
  }

  /// Attempts to authenticate the user with the provided [options], and using
  /// [strings] for any UI.
<<<<<<< HEAD
  Future<AuthResult> authenticate(
    AuthOptions options,
    AuthStrings strings,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.authenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options, strings],
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  Future<AuthResult> authenticate(
      AuthOptions options, AuthStrings strings) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.local_auth_android.LocalAuthApi.authenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
=======
  Future<AuthResult> authenticate(AuthOptions options, AuthStrings strings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.authenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    );
    final List<Object?>? pigeonVar_replyList =
<<<<<<< HEAD
        await pigeonVar_sendFuture as List<Object?>?;
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    final List<Object?>? pigeonVar_replyList = await pigeonVar_channel
        .send(<Object?>[options, strings]) as List<Object?>?;
=======
        await pigeonVar_channel.send(<Object?>[options, strings]) as List<Object?>?;
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AuthResult?)!;
    }
  }

  /// Clear biometric checking variables
  Future<void> clearBiometricChecking() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.local_auth_android.LocalAuthApi.clearBiometricChecking$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
