// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
<<<<<<< HEAD
// Autogenerated from Pigeon (v26.1.0), do not edit directly.
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
// Autogenerated from Pigeon (v22.4.0), do not edit directly.
=======
// Autogenerated from Pigeon (v22.7.2), do not edit directly.
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
// See also: https://pub.dev/packages/pigeon

package io.flutter.plugins.localauth;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Possible outcomes of an authentication attempt. */
<<<<<<< HEAD
  public enum AuthResultCode {
    /** The user authenticated successfully. */
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
  public enum AuthResult {
    /** The user authenticated successfully. */
=======
  public enum AuthResult {
    /** The user authenticated successfully and no biometric checking was done. */
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    SUCCESS(0),
<<<<<<< HEAD
    /** The user pressed the negative button, which corresponds to [AuthStrings.cancelButton]. */
    NEGATIVE_BUTTON(1),
    /**
     * The user canceled authentication without pressing the negative button.
     *
     * <p>This may be triggered by a swipe or a back button, for example.
     */
    USER_CANCELED(2),
    /** Authentication was caneceled by the system. */
    SYSTEM_CANCELED(3),
    /** Authentication timed out. */
    TIMEOUT(4),
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    /** The user failed to successfully authenticate. */
    FAILURE(1),
=======
    /** The user authenticated successfully, and biometric checking was true. */
    SUCCESS_VALIDATED(1),
    /** The user authenticated successfully, and biometric checking was false. */
    SUCCESS_INVALIDATED(2),
    /** The user failed to successfully authenticate. */
    FAILURE(3),
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** An authentication was already in progress. */
<<<<<<< HEAD
    ALREADY_IN_PROGRESS(5),
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    ERROR_ALREADY_IN_PROGRESS(2),
=======
    ERROR_ALREADY_IN_PROGRESS(4),
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** There is no foreground activity. */
<<<<<<< HEAD
    NO_ACTIVITY(6),
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    ERROR_NO_ACTIVITY(3),
=======
    ERROR_NO_ACTIVITY(5),
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** The foreground activity is not a FragmentActivity. */
<<<<<<< HEAD
    NOT_FRAGMENT_ACTIVITY(7),
    /** The device does not have any credentials available. */
    NO_CREDENTIALS(8),
    /** No biometric hardware is present. */
    NO_HARDWARE(9),
    /** The biometric is temporarily unavailable. */
    HARDWARE_UNAVAILABLE(10),
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    ERROR_NOT_FRAGMENT_ACTIVITY(4),
    /** The authentication system was not available. */
    ERROR_NOT_AVAILABLE(5),
=======
    ERROR_NOT_FRAGMENT_ACTIVITY(6),
    /** The authentication system was not available. */
    ERROR_NOT_AVAILABLE(7),
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** No biometrics are enrolled. */
<<<<<<< HEAD
    NOT_ENROLLED(11),
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    ERROR_NOT_ENROLLED(6),
=======
    ERROR_NOT_ENROLLED(8),
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** The user is locked out temporarily due to too many failed attempts. */
<<<<<<< HEAD
    LOCKED_OUT_TEMPORARILY(12),
    /** The user is locked out until they log in another way due to too many failed attempts. */
    LOCKED_OUT_PERMANENTLY(13),
    /** The device does not have enough storage to complete authentication. */
    NO_SPACE(14),
    /** The hardware is unavailable until a security update is performed. */
    SECURITY_UPDATE_REQUIRED(15),
    /** Some unrecognized error case was encountered */
    UNKNOWN_ERROR(16);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    ERROR_LOCKED_OUT_TEMPORARILY(7),
    /** The user is locked out until they log in another way due to too many failed attempts. */
    ERROR_LOCKED_OUT_PERMANENTLY(8);
=======
    ERROR_LOCKED_OUT_TEMPORARILY(9),
    /**
     * The user is locked out until they log in another way due to too many
     * failed attempts.
     */
    ERROR_LOCKED_OUT_PERMANENTLY(10),
    /** Biometric checking failed. */
    ERROR_BIOMETRIC_CHECKING(11);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)

    final int index;

    AuthResultCode(final int index) {
      this.index = index;
    }
  }

  /** Pigeon equivalent of the subset of BiometricType used by Android. */
  public enum AuthClassification {
    WEAK(0),
    STRONG(1);

    final int index;

    AuthClassification(final int index) {
      this.index = index;
    }
  }

  /**
   * Pigeon version of AndroidAuthStrings, plus the authorization reason.
   *
   * See auth_messages_android.dart for details.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class AuthStrings {
    private @NonNull String reason;

    public @NonNull String getReason() {
      return reason;
    }

    public void setReason(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"reason\" is null.");
      }
      this.reason = setterArg;
    }

    private @NonNull String signInHint;

    public @NonNull String getSignInHint() {
      return signInHint;
    }

    public void setSignInHint(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"signInHint\" is null.");
      }
      this.signInHint = setterArg;
    }

    private @NonNull String cancelButton;

    public @NonNull String getCancelButton() {
      return cancelButton;
    }

    public void setCancelButton(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"cancelButton\" is null.");
      }
      this.cancelButton = setterArg;
    }

<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    private @NonNull String deviceCredentialsRequiredTitle;

    public @NonNull String getDeviceCredentialsRequiredTitle() {
      return deviceCredentialsRequiredTitle;
    }

    public void setDeviceCredentialsRequiredTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException(
            "Nonnull field \"deviceCredentialsRequiredTitle\" is null.");
      }
      this.deviceCredentialsRequiredTitle = setterArg;
    }

    private @NonNull String deviceCredentialsSetupDescription;

    public @NonNull String getDeviceCredentialsSetupDescription() {
      return deviceCredentialsSetupDescription;
    }

    public void setDeviceCredentialsSetupDescription(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException(
            "Nonnull field \"deviceCredentialsSetupDescription\" is null.");
      }
      this.deviceCredentialsSetupDescription = setterArg;
    }

    private @NonNull String goToSettingsButton;

    public @NonNull String getGoToSettingsButton() {
      return goToSettingsButton;
    }

    public void setGoToSettingsButton(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"goToSettingsButton\" is null.");
      }
      this.goToSettingsButton = setterArg;
    }

    private @NonNull String goToSettingsDescription;

    public @NonNull String getGoToSettingsDescription() {
      return goToSettingsDescription;
    }

    public void setGoToSettingsDescription(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"goToSettingsDescription\" is null.");
      }
      this.goToSettingsDescription = setterArg;
    }

=======
    private @NonNull String deviceCredentialsRequiredTitle;

    public @NonNull String getDeviceCredentialsRequiredTitle() {
      return deviceCredentialsRequiredTitle;
    }

    public void setDeviceCredentialsRequiredTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"deviceCredentialsRequiredTitle\" is null.");
      }
      this.deviceCredentialsRequiredTitle = setterArg;
    }

    private @NonNull String deviceCredentialsSetupDescription;

    public @NonNull String getDeviceCredentialsSetupDescription() {
      return deviceCredentialsSetupDescription;
    }

    public void setDeviceCredentialsSetupDescription(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"deviceCredentialsSetupDescription\" is null.");
      }
      this.deviceCredentialsSetupDescription = setterArg;
    }

    private @NonNull String goToSettingsButton;

    public @NonNull String getGoToSettingsButton() {
      return goToSettingsButton;
    }

    public void setGoToSettingsButton(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"goToSettingsButton\" is null.");
      }
      this.goToSettingsButton = setterArg;
    }

    private @NonNull String goToSettingsDescription;

    public @NonNull String getGoToSettingsDescription() {
      return goToSettingsDescription;
    }

    public void setGoToSettingsDescription(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"goToSettingsDescription\" is null.");
      }
      this.goToSettingsDescription = setterArg;
    }

>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    private @NonNull String signInTitle;

    public @NonNull String getSignInTitle() {
      return signInTitle;
    }

    public void setSignInTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"signInTitle\" is null.");
      }
      this.signInTitle = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AuthStrings() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthStrings that = (AuthStrings) o;
<<<<<<< HEAD
      return reason.equals(that.reason)
          && signInHint.equals(that.signInHint)
          && cancelButton.equals(that.cancelButton)
          && signInTitle.equals(that.signInTitle);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      return reason.equals(that.reason)
          && biometricHint.equals(that.biometricHint)
          && biometricNotRecognized.equals(that.biometricNotRecognized)
          && biometricRequiredTitle.equals(that.biometricRequiredTitle)
          && cancelButton.equals(that.cancelButton)
          && deviceCredentialsRequiredTitle.equals(that.deviceCredentialsRequiredTitle)
          && deviceCredentialsSetupDescription.equals(that.deviceCredentialsSetupDescription)
          && goToSettingsButton.equals(that.goToSettingsButton)
          && goToSettingsDescription.equals(that.goToSettingsDescription)
          && signInTitle.equals(that.signInTitle);
=======
      return reason.equals(that.reason) && biometricHint.equals(that.biometricHint) && biometricNotRecognized.equals(that.biometricNotRecognized) && biometricRequiredTitle.equals(that.biometricRequiredTitle) && cancelButton.equals(that.cancelButton) && deviceCredentialsRequiredTitle.equals(that.deviceCredentialsRequiredTitle) && deviceCredentialsSetupDescription.equals(that.deviceCredentialsSetupDescription) && goToSettingsButton.equals(that.goToSettingsButton) && goToSettingsDescription.equals(that.goToSettingsDescription) && signInTitle.equals(that.signInTitle);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    }

    @Override
    public int hashCode() {
<<<<<<< HEAD
      return Objects.hash(reason, signInHint, cancelButton, signInTitle);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      return Objects.hash(
          reason,
          biometricHint,
          biometricNotRecognized,
          biometricRequiredTitle,
          cancelButton,
          deviceCredentialsRequiredTitle,
          deviceCredentialsSetupDescription,
          goToSettingsButton,
          goToSettingsDescription,
          signInTitle);
=======
      return Objects.hash(reason, biometricHint, biometricNotRecognized, biometricRequiredTitle, cancelButton, deviceCredentialsRequiredTitle, deviceCredentialsSetupDescription, goToSettingsButton, goToSettingsDescription, signInTitle);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    }

    public static final class Builder {

      private @Nullable String reason;

      @CanIgnoreReturnValue
      public @NonNull Builder setReason(@NonNull String setterArg) {
        this.reason = setterArg;
        return this;
      }

      private @Nullable String signInHint;

      @CanIgnoreReturnValue
      public @NonNull Builder setSignInHint(@NonNull String setterArg) {
        this.signInHint = setterArg;
        return this;
      }

      private @Nullable String cancelButton;

      @CanIgnoreReturnValue
      public @NonNull Builder setCancelButton(@NonNull String setterArg) {
        this.cancelButton = setterArg;
        return this;
      }

      private @Nullable String signInTitle;

      @CanIgnoreReturnValue
      public @NonNull Builder setSignInTitle(@NonNull String setterArg) {
        this.signInTitle = setterArg;
        return this;
      }

      public @NonNull AuthStrings build() {
        AuthStrings pigeonReturn = new AuthStrings();
        pigeonReturn.setReason(reason);
        pigeonReturn.setSignInHint(signInHint);
        pigeonReturn.setCancelButton(cancelButton);
        pigeonReturn.setSignInTitle(signInTitle);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(reason);
      toListResult.add(signInHint);
      toListResult.add(cancelButton);
      toListResult.add(signInTitle);
      return toListResult;
    }

    static @NonNull AuthStrings fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthStrings pigeonResult = new AuthStrings();
      Object reason = pigeonVar_list.get(0);
      pigeonResult.setReason((String) reason);
      Object signInHint = pigeonVar_list.get(1);
      pigeonResult.setSignInHint((String) signInHint);
      Object cancelButton = pigeonVar_list.get(2);
      pigeonResult.setCancelButton((String) cancelButton);
      Object signInTitle = pigeonVar_list.get(3);
      pigeonResult.setSignInTitle((String) signInTitle);
      return pigeonResult;
    }
  }

  /**
   * The results of an authentication request.
   *
   * <p>Generated class from Pigeon that represents data sent in messages.
   */
  public static final class AuthResult {
    /** The specific result returned from the SDK. */
    private @NonNull AuthResultCode code;

    public @NonNull AuthResultCode getCode() {
      return code;
    }

    public void setCode(@NonNull AuthResultCode setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"code\" is null.");
      }
      this.code = setterArg;
    }

    /** The error message associated with the result, if any. */
    private @Nullable String errorMessage;

    public @Nullable String getErrorMessage() {
      return errorMessage;
    }

    public void setErrorMessage(@Nullable String setterArg) {
      this.errorMessage = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    AuthResult() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }
      AuthResult that = (AuthResult) o;
      return code.equals(that.code) && Objects.equals(errorMessage, that.errorMessage);
    }

    @Override
    public int hashCode() {
      return Objects.hash(code, errorMessage);
    }

    public static final class Builder {

      private @Nullable AuthResultCode code;

      @CanIgnoreReturnValue
      public @NonNull Builder setCode(@NonNull AuthResultCode setterArg) {
        this.code = setterArg;
        return this;
      }

      private @Nullable String errorMessage;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorMessage(@Nullable String setterArg) {
        this.errorMessage = setterArg;
        return this;
      }

      public @NonNull AuthResult build() {
        AuthResult pigeonReturn = new AuthResult();
        pigeonReturn.setCode(code);
        pigeonReturn.setErrorMessage(errorMessage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(code);
      toListResult.add(errorMessage);
      return toListResult;
    }

    static @NonNull AuthResult fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthResult pigeonResult = new AuthResult();
      Object code = pigeonVar_list.get(0);
      pigeonResult.setCode((AuthResultCode) code);
      Object errorMessage = pigeonVar_list.get(1);
      pigeonResult.setErrorMessage((String) errorMessage);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class AuthOptions {
    private @NonNull Boolean biometricOnly;

    public @NonNull Boolean getBiometricOnly() {
      return biometricOnly;
    }

    public void setBiometricOnly(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"biometricOnly\" is null.");
      }
      this.biometricOnly = setterArg;
    }

    private @NonNull Boolean sensitiveTransaction;

    public @NonNull Boolean getSensitiveTransaction() {
      return sensitiveTransaction;
    }

    public void setSensitiveTransaction(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sensitiveTransaction\" is null.");
      }
      this.sensitiveTransaction = setterArg;
    }

    private @NonNull Boolean sticky;

    public @NonNull Boolean getSticky() {
      return sticky;
    }

    public void setSticky(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sticky\" is null.");
      }
      this.sticky = setterArg;
    }

<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    private @NonNull Boolean useErrorDialgs;

    public @NonNull Boolean getUseErrorDialgs() {
      return useErrorDialgs;
    }

    public void setUseErrorDialgs(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"useErrorDialgs\" is null.");
      }
      this.useErrorDialgs = setterArg;
    }

=======
    private @NonNull Boolean useErrorDialgs;

    public @NonNull Boolean getUseErrorDialgs() {
      return useErrorDialgs;
    }

    public void setUseErrorDialgs(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"useErrorDialgs\" is null.");
      }
      this.useErrorDialgs = setterArg;
    }

    private @NonNull Boolean checkBiometricInvalidationForKey;

    public @NonNull Boolean getCheckBiometricInvalidationForKey() {
      return checkBiometricInvalidationForKey;
    }

    public void setCheckBiometricInvalidationForKey(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"checkBiometricInvalidationForKey\" is null.");
      }
      this.checkBiometricInvalidationForKey = setterArg;
    }

>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    /** Constructor is non-public to enforce null safety; use Builder. */
    AuthOptions() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      AuthOptions that = (AuthOptions) o;
<<<<<<< HEAD
      return biometricOnly.equals(that.biometricOnly)
          && sensitiveTransaction.equals(that.sensitiveTransaction)
          && sticky.equals(that.sticky);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      return biometricOnly.equals(that.biometricOnly)
          && sensitiveTransaction.equals(that.sensitiveTransaction)
          && sticky.equals(that.sticky)
          && useErrorDialgs.equals(that.useErrorDialgs);
=======
      return biometricOnly.equals(that.biometricOnly) && sensitiveTransaction.equals(that.sensitiveTransaction) && sticky.equals(that.sticky) && useErrorDialgs.equals(that.useErrorDialgs) && checkBiometricInvalidationForKey.equals(that.checkBiometricInvalidationForKey);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    }

    @Override
    public int hashCode() {
<<<<<<< HEAD
      return Objects.hash(biometricOnly, sensitiveTransaction, sticky);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      return Objects.hash(biometricOnly, sensitiveTransaction, sticky, useErrorDialgs);
=======
      return Objects.hash(biometricOnly, sensitiveTransaction, sticky, useErrorDialgs, checkBiometricInvalidationForKey);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    }

    public static final class Builder {

      private @Nullable Boolean biometricOnly;

      @CanIgnoreReturnValue
      public @NonNull Builder setBiometricOnly(@NonNull Boolean setterArg) {
        this.biometricOnly = setterArg;
        return this;
      }

      private @Nullable Boolean sensitiveTransaction;

      @CanIgnoreReturnValue
      public @NonNull Builder setSensitiveTransaction(@NonNull Boolean setterArg) {
        this.sensitiveTransaction = setterArg;
        return this;
      }

      private @Nullable Boolean sticky;

      @CanIgnoreReturnValue
      public @NonNull Builder setSticky(@NonNull Boolean setterArg) {
        this.sticky = setterArg;
        return this;
      }

<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      private @Nullable Boolean useErrorDialgs;

      @CanIgnoreReturnValue
      public @NonNull Builder setUseErrorDialgs(@NonNull Boolean setterArg) {
        this.useErrorDialgs = setterArg;
        return this;
      }

=======
      private @Nullable Boolean useErrorDialgs;

      @CanIgnoreReturnValue
      public @NonNull Builder setUseErrorDialgs(@NonNull Boolean setterArg) {
        this.useErrorDialgs = setterArg;
        return this;
      }

      private @Nullable Boolean checkBiometricInvalidationForKey;

      @CanIgnoreReturnValue
      public @NonNull Builder setCheckBiometricInvalidationForKey(@NonNull Boolean setterArg) {
        this.checkBiometricInvalidationForKey = setterArg;
        return this;
      }

>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      public @NonNull AuthOptions build() {
        AuthOptions pigeonReturn = new AuthOptions();
        pigeonReturn.setBiometricOnly(biometricOnly);
        pigeonReturn.setSensitiveTransaction(sensitiveTransaction);
        pigeonReturn.setSticky(sticky);
<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
        pigeonReturn.setUseErrorDialgs(useErrorDialgs);
=======
        pigeonReturn.setUseErrorDialgs(useErrorDialgs);
        pigeonReturn.setCheckBiometricInvalidationForKey(checkBiometricInvalidationForKey);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
<<<<<<< HEAD
      ArrayList<Object> toListResult = new ArrayList<>(3);
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      ArrayList<Object> toListResult = new ArrayList<>(4);
=======
      ArrayList<Object> toListResult = new ArrayList<>(5);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      toListResult.add(biometricOnly);
      toListResult.add(sensitiveTransaction);
      toListResult.add(sticky);
<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      toListResult.add(useErrorDialgs);
=======
      toListResult.add(useErrorDialgs);
      toListResult.add(checkBiometricInvalidationForKey);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      return toListResult;
    }

    static @NonNull AuthOptions fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      AuthOptions pigeonResult = new AuthOptions();
      Object biometricOnly = pigeonVar_list.get(0);
      pigeonResult.setBiometricOnly((Boolean) biometricOnly);
      Object sensitiveTransaction = pigeonVar_list.get(1);
      pigeonResult.setSensitiveTransaction((Boolean) sensitiveTransaction);
      Object sticky = pigeonVar_list.get(2);
      pigeonResult.setSticky((Boolean) sticky);
<<<<<<< HEAD
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
      Object useErrorDialgs = pigeonVar_list.get(3);
      pigeonResult.setUseErrorDialgs((Boolean) useErrorDialgs);
=======
      Object useErrorDialgs = pigeonVar_list.get(3);
      pigeonResult.setUseErrorDialgs((Boolean) useErrorDialgs);
      Object checkBiometricInvalidationForKey = pigeonVar_list.get(4);
      pigeonResult.setCheckBiometricInvalidationForKey((Boolean) checkBiometricInvalidationForKey);
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
<<<<<<< HEAD
        case (byte) 129:
          {
            Object value = readValue(buffer);
            return value == null ? null : AuthResultCode.values()[((Long) value).intValue()];
          }
        case (byte) 130:
          {
            Object value = readValue(buffer);
            return value == null ? null : AuthClassification.values()[((Long) value).intValue()];
          }
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
        case (byte) 129:
          {
            Object value = readValue(buffer);
            return value == null ? null : AuthResult.values()[((Long) value).intValue()];
          }
        case (byte) 130:
          {
            Object value = readValue(buffer);
            return value == null ? null : AuthClassification.values()[((Long) value).intValue()];
          }
=======
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : AuthResult.values()[((Long) value).intValue()];
        }
        case (byte) 130: {
          Object value = readValue(buffer);
          return value == null ? null : AuthClassification.values()[((Long) value).intValue()];
        }
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
        case (byte) 131:
          return AuthStrings.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return AuthResult.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return AuthOptions.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof AuthResultCode) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((AuthResultCode) value).index);
      } else if (value instanceof AuthClassification) {
        stream.write(130);
        writeValue(stream, value == null ? null : ((AuthClassification) value).index);
      } else if (value instanceof AuthStrings) {
        stream.write(131);
        writeValue(stream, ((AuthStrings) value).toList());
      } else if (value instanceof AuthResult) {
        stream.write(132);
        writeValue(stream, ((AuthResult) value).toList());
      } else if (value instanceof AuthOptions) {
        stream.write(133);
        writeValue(stream, ((AuthOptions) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface LocalAuthApi {
    /** Returns true if this device supports authentication. */
    @NonNull 
    Boolean isDeviceSupported();
    /**
     * Returns true if this device can support biometric authentication, whether
     * any biometrics are enrolled or not.
     */
    @NonNull 
    Boolean deviceCanSupportBiometrics();
    /**
     * Cancels any in-progress authentication.
     *
     * Returns true only if authentication was in progress, and was successfully
     * cancelled.
     */
    @NonNull 
    Boolean stopAuthentication();
    /**
<<<<<<< HEAD
     * Returns the biometric types that are enrolled, and can thus be used without additional setup.
     *
     * <p>Returns null if there is no activity, in which case the enrolled biometrics can't be
     * determined.
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
     * Returns the biometric types that are enrolled, and can thus be used without additional setup.
=======
     * Returns the biometric types that are enrolled, and can thus be used
     * without additional setup.
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
     */
<<<<<<< HEAD
    @Nullable
||||||| parent of bfc81e78e ([local_auth] Add Biometric Checking)
    @NonNull
=======
    @NonNull 
>>>>>>> bfc81e78e ([local_auth] Add Biometric Checking)
    List<AuthClassification> getEnrolledBiometrics();
    /**
     * Attempts to authenticate the user with the provided [options], and using
     * [strings] for any UI.
     */
    void authenticate(@NonNull AuthOptions options, @NonNull AuthStrings strings, @NonNull Result<AuthResult> result);
    /** Clear biometric checking variables */
    void clearBiometricChecking();

    /** The codec used by LocalAuthApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `LocalAuthApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable LocalAuthApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable LocalAuthApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.isDeviceSupported" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Boolean output = api.isDeviceSupported();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.deviceCanSupportBiometrics" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Boolean output = api.deviceCanSupportBiometrics();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.stopAuthentication" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Boolean output = api.stopAuthentication();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.getEnrolledBiometrics" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  List<AuthClassification> output = api.getEnrolledBiometrics();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.authenticate" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                AuthOptions optionsArg = (AuthOptions) args.get(0);
                AuthStrings stringsArg = (AuthStrings) args.get(1);
                Result<AuthResult> resultCallback =
                    new Result<AuthResult>() {
                      public void success(AuthResult result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.authenticate(optionsArg, stringsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.local_auth_android.LocalAuthApi.clearBiometricChecking" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.clearBiometricChecking();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
